name: Deploy to Github Pages 🚀
on: [workflow_call, workflow_dispatch]

jobs:
  deployPages:
      name: Deploy to Github Pages 🚀 🕸 
      runs-on: ubuntu-latest
      steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - uses: actions/download-artifact@v3
         with:
           name: build-WebGL
           path: build

       - name: Display structure of root files
         run: ls -R
         working-directory: build/WebGL

       - name: Deploy 🚀
         uses: JamesIves/github-pages-deploy-action@4.1.4
         with:
           branch: gh-pages
           folder: build/WebGL